package data

// Generated by genfront -- do not edit this file.

func (dest *Item) FullUpdateDest(src Item) {
	dest.Id = src.Id
	dest.GroupId = src.GroupId
	dest.CreatedOn = src.CreatedOn
	dest.CreatedBy = src.CreatedBy
	dest.UpdatedOn = src.UpdatedOn
	dest.UpdatedBy = src.UpdatedBy
	dest.Url = src.Url
	dest.Title = src.Title
	dest.Description = src.Description
	dest.Tags = src.Tags
	dest.FavoritedBy = src.FavoritedBy
	dest.Position = src.Position
	dest.Security = src.Security
	dest.ItemState = src.ItemState
	dest.RecordStatus = src.RecordStatus
}

func (src Item) Copy() Item {
	dest := &Item{}
	dest.FullUpdateDest(src)
	return *dest
}
