// Code generated by "stringer -type=RecordStatus"; DO NOT EDIT

package data

import "fmt"

const _RecordStatus_name = "ActiveDeleted"

var _RecordStatus_index = [...]uint8{0, 6, 13}

func (i RecordStatus) String() string {
	i -= 1
	if i < 0 || i >= RecordStatus(len(_RecordStatus_index)-1) {
		return fmt.Sprintf("RecordStatus(%d)", i+1)
	}
	return _RecordStatus_name[_RecordStatus_index[i]:_RecordStatus_index[i+1]]
}
