package data

// Generated by genfront -- do not edit this file.

func (dest *User) FullUpdateDest(src User) {
	dest.Id = src.Id
	dest.GroupId = src.GroupId
	dest.CreatedOn = src.CreatedOn
	dest.CreatedBy = src.CreatedBy
	dest.UpdatedOn = src.UpdatedOn
	dest.UpdatedBy = src.UpdatedBy
	dest.Username = src.Username
	dest.Password = src.Password
	dest.FirstName = src.FirstName
	dest.LastName = src.LastName
	dest.Email = src.Email
	dest.Icon = src.Icon
	dest.RecordStatus = src.RecordStatus
	dest.UserState = src.UserState
	dest.UserRole = src.UserRole
}

func (src User) Copy() User {
	dest := &User{}
	dest.FullUpdateDest(src)
	return *dest
}
