// Code generated by "stringer -type=UserState"; DO NOT EDIT

package data

import "fmt"

const _UserState_name = "NormalDisabledLocked"

var _UserState_index = [...]uint8{0, 6, 14, 20}

func (i UserState) String() string {
	i -= 1
	if i < 0 || i >= UserState(len(_UserState_index)-1) {
		return fmt.Sprintf("UserState(%d)", i+1)
	}
	return _UserState_name[_UserState_index[i]:_UserState_index[i+1]]
}
